on:
  push:
    branches: [ develop, bugfix/*, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build-validation:
    uses: abbgrade/PsBuildTasks/.github/workflows/build-validation-windows.yml@8fb9f78ac5fe8d5fa3023af6086474a3508c49d0
