on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    uses: abbgrade/PsBuildTasks/.github/workflows/release-windows.yml@1.4.0
    with:
      module-name: PsSmo
    secrets:
      ps-gallery-key: ${{ secrets.PS_GALLERY_KEY }}
