on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    uses: abbgrade/PsBuildTasks/.github/workflows/release-windows.yml@0e4c22414fdb3ec06288a3e2668a9b2e7d4a41dc
    with:
      module-name: PsSmo
    secrets:
      ps-gallery-key: ${{ secrets.PS_GALLERY_KEY }}
